CREATE TABLE IF NOT EXISTS files (
    `id` INT NOT NULL AUTO_INCREMENT,
    `fileName` VARCHAR(150) NOT NULL,
    `originalName` VARCHAR(150) NOT NULL,
    `fileSize` DECIMAL NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);